apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-a
  labels:
    app: service-a
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: service-a